### PR TITLE
Test refactor

### PR DESCRIPTION
**Pull request by ParkerLockhart**
PR includes: 

-universal test files 
-updated file paths in stat_tracker, runner, and stat_tracker_spec files
-updated expect statements in spec file
-fixed ends

### CODE REVIEW

**Comment by ParkerLockhart** [comment]
@all-contributors please add @ParkerLockhart  for League Statistics
@all-contributors please add @jbreit88  for Game Statistics
@all-contributors please add @joeldenverdev  for Team Statistics
@all-contributors please add @jgrazulis  for Season Statistics

**Comment by ParkerLockhart** [comment]
@all-contributors please add @ParkerLockhart for code
@all-contributors please add @jbreit88 for code
@all-contributors please add @joeldenverdev for code
@all-contributors please add @jgrazulis for code

**Comment by ParkerLockhart** [comment]
@all-contributors please add @ParkerLockhart  for code

**Comment by ParkerLockhart** [comment]
@all-contributors please add @joeldenverdev  for test

**Review by joel-grant — APPROVED** [review]
Yesss.  Thanks for fixing the end issues in spec.

**Pull request merged**
