### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by joel-grant**
Includes:
- `Game` class and `initialize`.
- `GameTeam` class and `initialize`
- `Team` class and `initialize`.
- Add 3 methods for reading files and creating objects in `StatTracker`.
- Method calls in `runner.rb`

### CODE REVIEW

**Comment by jgrazulis** [comment]
Thanks for setting that up, Joel!

**Comment by ParkerLockhart** [comment]
Hooray! We have a project skeleton.

**Review by ParkerLockhart — APPROVED** [review]

**Comment by jbreit88** [comment]
This commit allows us to access the data in the CSV files through class variables in the StatTracker class. With this complete we should now be able to write methods in the StatTracker class for iteration 2.

**Review by jbreit88 — APPROVED** [review]

**Review by jbreit88 — APPROVED** [review]
Just some simple adds

**Review by ParkerLockhart — APPROVED** [review]
Its working, its working!

**Comment by jgrazulis** [comment]
Woo we can work on statistic methods now!

**Review by jgrazulis — COMMENTED** [review]
Looks great;  looking forward to trying out all the methods in the stat tracker file

**Pull request merged**
